# Site settings
title: Wade Wegner
email: your_email@example.com
author: Wade Wegner
description: "From the whiteboard to the keyboard."
baseurl: ""
url: http://www.wadewegner.com

# Build settings
encoding: utf-8
markdown: redcarpet #kramdown
paginate: 5
permalink: /:year/:month/:title/

# Social
google_analytics: UA-1174672-2

# Sitemap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/rss.xml"
    include_posts:
        - "/index.html"
#    change_frequency_name: "change_frequency"
#    priority_name: "priority"

# Indexing settings
indextank_index: wadewegner
indextank_api_url: http://:ebadebadasab@ynereh.api.indexden.com

# these values are applied as regular expressions 
indextank_excludes: [index.html, 404.html, ^/secret/]